[book]
authors = ["Matthew Perry"]
language = "en"
multilingual = false
src = "src"
title = "Matthew Perry's Wiki"

[build]
create-missing = true

[output.html]
theme = "src/theme"
git-repository-url = "https://github.com/MattPerry1216/wiki"
curly-quotes = true # Shoutout to pratical typography
